global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'event-management'
    metrics_path: '/manage/prometheus'
    static_configs:
      - targets: ['event-management:8081']
    relabel_configs:
      - target_label: job
        replacement: "spring-actuator"

  - job_name: 'user-service'
    metrics_path: '/manage/prometheus'
    static_configs:
      - targets: ['user-service:8081']
    relabel_configs:
      - target_label: job
        replacement: "spring-actuator"