apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-management
  template:
    metadata:
      labels:
        app: event-management
    spec:
      automountServiceAccountToken: false
      containers:
        - name: event-management
          image: foxxxxx333/event-management:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-event:5432/eventdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "eventuser"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "eventpass"
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: user-service-secret
                  key: internal-api-key

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /manage/health/readiness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /manage/health/liveness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: event-management
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: event-management
