spring:
  application:
    name: event-management-service
  security:
    user:
      name: ${ACTUATOR_USER:admin}
      password: ${ACTUATOR_PASSWORD:admin}
      roles: ADMIN
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  boot:
    admin:
      client:
        url: ${SBA_URL:http://admin-telemetry-service:9090}
        username: ${SBA_USER:admin}
        password: ${SBA_PASSWORD:admin}
        instance:
          management-base-url: ${MANAGEMENT_BASE_URL:http://event-management:8081}
          metadata:
            user.name: ${ACTUATOR_USER:admin}
            user.password: ${ACTUATOR_PASSWORD:admin}

server:
  port: 8080

user:
  service:
    url: ${USER_SERVICE_BASE_URL:http://user-service:8080}

logging:
  level:
    org.springframework.retry: DEBUG
    org.springframework.cloud.openfeign: INFO
    root: INFO
  file:
    name: /app/logs/event-management-service.log

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
    logfile:
      enabled: true
      external-file: /app/logs/event-management-service.log
    loggers:
      enabled: true
    env:
      show-values: when_authorized
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
    enable:
      jvm: true
      system: true
      process: true
      http: true
      jdbc: true
      logback: true
      application: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        enabled: true
        url: http://otel-lgtm:4318/v1/metrics
    tracing:
      endpoint: http://otel-lgtm:4318/v1/traces
    logging:
      export:
        enabled: true
      endpoint: http://otel-lgtm:4318/v1/logs

internal:
  api:
    key: ${INTERNAL_API_KEY}
