spring:
  application:
    name: event-management-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
server:
  port: 8080

user:
  service:
    url: ${USER_SERVICE_BASE_URL:http://user-service:8080}

logging:
  level:
    org.springframework.retry: DEBUG
    org.springframework.cloud.openfeign: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

internal:
  api:
    key: ${INTERNAL_API_KEY}

grpc:
  client:
    user-service:
      address: "static://user-service:9090"
      negotiationType: plaintext