spring:
  application:
    name: event-management-service
  security:
    user:
      name: event-management-admin
      password: change-me
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  port: 8080

user:
  service:
    url: ${USER_SERVICE_BASE_URL:http://user-service:8080}

logging:
  level:
    org.springframework.retry: DEBUG
    org.springframework.cloud.openfeign: INFO

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true

internal:
  api:
    key: ${INTERNAL_API_KEY}
