spring:
  application:
    name: event-management-service
  security:
    user:
      name: ${ACTUATOR_USER:event-management-admin}
      password: ${ACTUATOR_PASSWORD:change-me}
      roles: ADMIN
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  boot:
    admin:
      client:
        url: ${SBA_URL:http://admin-telemetry-service:9090}
        username: ${SBA_USER:event-management-admin}
        password: ${SBA_PASSWORD:change-me}
        instance:
          management-base-url: ${MANAGEMENT_BASE_URL:http://user-service:8081}
          metadata:
            user.name: ${ACTUATOR_USER:event-management-admin}
            user.password: ${ACTUATOR_PASSWORD:change-me}

server:
  port: 8080

user:
  service:
    url: ${USER_SERVICE_BASE_URL:http://user-service:8080}

logging:
  level:
    org.springframework.retry: DEBUG
    org.springframework.cloud.openfeign: INFO

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true

internal:
  api:
    key: ${INTERNAL_API_KEY}
